name: build-debug-image

on:
  push:
    branches: [ master ]
    paths:
      - Dockerfile.debug

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build debug image
      uses: docker/build-push-action@v1
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        registry: registry.cn-beijing.aliyuncs.com
        repository: mengli/obs-headless-debug
        tags: latest
