name: obs-headless-pipeline

on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]

env:
  REGISTRY: registry.cn-beijing.aliyuncs.com/mengli

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use docker layer cache to speed up the build
      uses: satackey/action-docker-layer-caching@v0.0.3

    - name: Docker build
      run: docker build --rm -t ${REGISTRY}/obs-headless:latest .

    - name: Docker login for push
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login registry.cn-beijing.aliyuncs.com --username=${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Docker push
      run: docker push ${REGISTRY}/obs-headless:latest

